In [3]:
import pandas as pd
import numpy as np


In [7]:
from sklearn.datasets import load_iris
iris_dataset=load_iris()

In [8]:
print("keys of iris dataset: \n{}".format(iris_dataset.keys()))

keys of iris dataset: 
dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [9]:
val=iris_dataset["DESCR"]
start_val=val[:200]
print(start_val + "\n....")

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive
....


In [12]:
print("Target Names: {}".format(iris_dataset['target_names']))

Target Names: ['setosa' 'versicolor' 'virginica']


In [18]:
print("first seven rows of: {}".format(iris_dataset['data'][:7]))

first seven rows of: [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]]


In [14]:
print("frame: {}".format(iris_dataset['frame']))

frame: None


In [15]:
print("feature Names: {}".format(iris_dataset['feature_names']))

feature Names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [16]:
print("Shape of data {}".format(iris_dataset['data'].shape))

Shape of data (150, 4)


In [19]:
print("shape of target: {}".format(iris_dataset['target'].shape))

shape of target: (150,)


In [20]:
print("Target: {}".format(iris_dataset['target']))

Target: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train,y_test= train_test_split(
                            iris_dataset['data'], iris_dataset['target'], random_state=0)

In [23]:
print("X_train shape: {}".format(X_train.shape))
print("X_test shape: {}".format(X_test.shape))
print("y_train shape: {}".format(y_train.shape))
print("y_test shape: {}".format(y_test.shape))

X_train shape: (112, 4)
X_test shape: (38, 4)
y_train shape: (112,)
y_test shape: (38,)


In [28]:
from sklearn.neighbors import KNeighborsClassifier
knn= KNeighborsClassifier(n_neighbors=1)

In [31]:
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=1)

In [35]:
KNeighborsClassifier(n_neighbors=1).fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=1)

In [37]:
X_new=np.array([[5,2.9,1,0.2]])
print("X_new shape: {}".format(X_new.shape))

X_new shape: (1, 4)


In [40]:
prediction=knn.predict(X_new)
print("Prediction: {}".format(prediction))
print("Predicted dataset name: {}".format(iris_dataset['target_names'][prediction]))


Prediction: [0]
Predicted dataset name: ['setosa']


In [42]:
y_pred=knn.predict(X_test)
print("test set predictions: \n {}".format(y_pred))

test set predictions: 
 [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


In [43]:
print("test set score: {}".format(np.mean(y_pred==y_test)))

test set score: 0.9736842105263158
